/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UsrDetail.java
 *
 * Created on 28 Jan, 2012, 9:19:37 PM
 */
package com.my.cryptC;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author rajiv
 */
public class UsrDetail extends javax.swing.JFrame {
    
    public static String[] usrdetl;
    private int open;
    private File usrdtl;
    private File usrlog;
    protected FileWriter fstream;
    protected BufferedWriter out;
    protected BufferedReader br;
    /** Creates new form UsrDetail */
    public UsrDetail() {
        open=InitWindow.openform;
        initComponents();
        usrdetl=new String[5];
        usrdtl=new File("./Log/UserDetail.txt");
                
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usrname = new javax.swing.JTextField();
        usrid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        phn_Num = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Clg_Field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        email_Field = new javax.swing.JTextField();
        pcNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.lightGray);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        usrname.setBackground(java.awt.Color.lightGray);
        usrname.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        usrname.setForeground(new java.awt.Color(1, 1, 1));

        usrid.setBackground(java.awt.Color.lightGray);
        usrid.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        usrid.setForeground(new java.awt.Color(1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18));
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18));
        jLabel2.setText("Laqshya ID");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18));
        jLabel3.setText("Mobile Number");

        phn_Num.setBackground(java.awt.Color.lightGray);
        phn_Num.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        phn_Num.setForeground(new java.awt.Color(1, 1, 1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18));
        jLabel4.setText("Institute Name");

        Clg_Field.setBackground(java.awt.Color.lightGray);
        Clg_Field.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        Clg_Field.setForeground(new java.awt.Color(1, 1, 1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18));
        jLabel5.setText("Email ID");

        email_Field.setBackground(java.awt.Color.lightGray);
        email_Field.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        email_Field.setForeground(new java.awt.Color(1, 1, 1));

        pcNo.setBackground(java.awt.Color.lightGray);
        pcNo.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        pcNo.setForeground(new java.awt.Color(1, 1, 1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18));
        jLabel6.setText("PC no");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pcNo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Clg_Field, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email_Field, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usrname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(usrid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(phn_Num, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usrname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usrid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(phn_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(email_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clg_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pcNo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButton1.setBackground(java.awt.Color.darkGray);
        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jButton1.setForeground(new java.awt.Color(248, 247, 243));
        jButton1.setText("Next >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.darkGray);
        jButton2.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jButton2.setForeground(new java.awt.Color(248, 247, 243));
        jButton2.setText("Exit !!");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel7.setText("Developed by : Rajiv Singh & Annim Banerjee");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void logsaver(String filename){
    File logfile =new File(filename);
    usrdetl[0]="UserName:-"+usrname.getText();
    usrdetl[1]="UserID:-"+usrid.getText();
    usrdetl[2]= "phn_Num:-"+phn_Num.getText();
    usrdetl[3]= "email_ID:-"+email_Field.getText();
    usrdetl[4]= "College_Name:-"+Clg_Field.getText();
        try {
            fstream = new FileWriter(logfile);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
                out = new BufferedWriter(fstream);
                
                //while(jTextArea1.read)
               for(int i=0;i<5;i++) {
            try {
                out.write(usrdetl[i]+"\n");
                
            } catch (IOException ex) {
                
                ex.printStackTrace();
            }
               }
        try {
            out.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
}
private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
    int x =JOptionPane.showConfirmDialog(this,"Are you sure","Cryptic-C",JOptionPane.YES_NO_OPTION);
    if(x==JOptionPane.YES_OPTION){        
    System.exit(0);
    }// TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    if(phn_Num.getText().length()!=10){
        JOptionPane.showMessageDialog(null, "Please Enter correct Information", "Cryptic_C", JOptionPane.INFORMATION_MESSAGE);
    
    }
    else{     
                logsaver("./vLog/UserDetail.txt");
    if(usrname.getText().equals("") && usrid.getText().equals(""))
            {
                 JOptionPane.showMessageDialog(this,"Please fill your details first !!","Cryptic-C",JOptionPane.INFORMATION_MESSAGE);
            }
             else
            {   
                    if(open==1){
                     logsaver("./r1Log/"+usrid.getText()+".txt");    
                    Round1.main(null);
                    this.dispose();
                    }
                    
                   else if(open==2){
                        logsaver("./r2Log/"+usrid.getText()+".txt");
                    Round2.main(null);
                    this.dispose();
                    }
                    
                   else if(open==3){
                        logsaver("./r3Log/"+usrid.getText()+".txt");
                    Round3.main(null);
                    this.dispose();
                    }
            }      // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsrDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsrDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsrDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsrDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UsrDetail().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Clg_Field;
    public static javax.swing.JTextField email_Field;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField pcNo;
    public static javax.swing.JTextField phn_Num;
    public static javax.swing.JTextField usrid;
    public static javax.swing.JTextField usrname;
    // End of variables declaration//GEN-END:variables
}
